import { Nunito_Sans } from 'next/font/google';
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import AboveFooter from "@/components/AboveFooter";
import BottomFooter from "@/components/BottomFooter";

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: "#000000",
  initialScale: 1,
  width: "device-width",
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
        {/* Add any other head elements here */}
      </head>
      <body className={`${nunitoSans.className} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {children}
        <AboveFooter />
        <BottomFooter />
      </body>
    </html>
  );
}
